In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from lightgbm import LGBMClassifier
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("../GTZAN/Data/features_30_sec.csv")
df = data.sample(frac=1).reset_index(drop=True)
df.head()

filename  length  chroma_stft_mean  chroma_stft_var  rms_mean  \
0    rock.00045.wav  661794          0.361234         0.082603  0.096995   
1  reggae.00041.wav  661504          0.373656         0.091907  0.119993   
2    rock.00035.wav  661794          0.457206         0.079384  0.124158   
3    rock.00094.wav  661794          0.389313         0.073420  0.101960   
4   blues.00006.wav  661794          0.291328         0.093981  0.141874   

    rms_var  spectral_centroid_mean  spectral_centroid_var  \
0  0.000815             1560.999792           90382.491401   
1  0.000973             1930.232326          589491.544262   
2  0.000459             1867.082394          398470.110770   
3  0.000372             2628.863788           93936.455555   
4  0.008803             1459.366472          437859.398051   

   spectral_bandwidth_mean  spectral_bandwidth_var  ...  mfcc16_var  \
0              1568.308311            10787.185064  ...   25.971584   
1              2204.904559           155397.743357  ...   49.393574   
2              2422.014649           281438.579580  ...   24.703766   
3              2210.478936            37253.811076  ...   26.217716   
4              1389.009131           185023.239545  ...   83.248245   

   mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  \
0   -11.281557   17.765968    -7.829482   20.357563    -7.715235   21.045958   
1    -1.406729   81.619194    -1.651171   53.031818     1.212168   56.808544   
2    -0.031292   29.246223    -1.009292   24.503607    -5.568185   31.999117   
3   -12.762190   24.685890     2.999796   31.530489    -6.408553   31.573473   
4   -10.913176   56.902153    -6.971336   38.231800    -3.436505   48.235741   

   mfcc20_mean  mfcc20_var   label  
0    -8.141011   21.702080    rock  
1    -1.888977   54.328857  reggae  
2    -0.845786   34.502522    rock  
3     2.254876   38.511021    rock  
4    -6.483466   70.170364   blues  

[5 rows x 60 columns]

In [3]:
dummy = df.drop(['filename', 'length'], axis=1)
column_name = 'label'
label_encoder = LabelEncoder()
dummy[column_name] = label_encoder.fit_transform(dummy[column_name])
corr = dummy.corr()
corr_style = corr.style.background_gradient(cmap='coolwarm')
display(corr_style)

In [4]:
label_encoder = LabelEncoder()
target = "label"
x = df.drop(['filename', 'length',target], axis=1)
y = df[target]
y= label_encoder.fit_transform(y)
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, stratify=y, random_state=100)
y

array([9, 8, 9, 9, 0, 4, 7, 7, 3, 5, 0, 7, 5, 9, 0, 8, 1, 5, 4, 5, 4, 6,
       3, 8, 1, 8, 1, 8, 8, 8, 6, 1, 8, 5, 6, 0, 7, 0, 7, 5, 8, 6, 4, 9,
       9, 9, 8, 0, 1, 3, 4, 8, 5, 9, 0, 1, 7, 1, 0, 4, 9, 7, 3, 5, 3, 3,
       2, 9, 4, 8, 8, 6, 8, 9, 5, 9, 4, 7, 5, 6, 6, 1, 9, 2, 4, 0, 4, 0,
       0, 9, 4, 4, 7, 3, 6, 7, 9, 7, 7, 2, 8, 3, 9, 6, 4, 9, 1, 9, 8, 1,
       9, 5, 1, 6, 2, 7, 1, 6, 3, 5, 2, 3, 8, 4, 4, 6, 4, 6, 5, 4, 3, 4,
       7, 6, 5, 3, 7, 7, 4, 2, 5, 6, 7, 2, 1, 1, 2, 5, 2, 0, 1, 6, 0, 2,
       8, 0, 4, 3, 0, 5, 4, 2, 1, 0, 0, 1, 2, 9, 2, 5, 6, 9, 4, 5, 1, 7,
       5, 9, 3, 3, 9, 8, 6, 5, 7, 7, 6, 3, 7, 7, 5, 1, 0, 9, 7, 7, 3, 8,
       6, 0, 8, 6, 7, 4, 4, 2, 5, 0, 7, 3, 8, 7, 1, 3, 4, 0, 3, 0, 1, 5,
       1, 1, 5, 0, 7, 6, 8, 1, 3, 1, 4, 8, 1, 8, 7, 2, 1, 4, 0, 6, 8, 5,
       7, 0, 8, 0, 9, 3, 0, 7, 5, 0, 0, 8, 7, 9, 6, 3, 0, 7, 0, 9, 6, 3,
       3, 0, 3, 0, 0, 2, 2, 6, 3, 9, 6, 1, 7, 5, 9, 6, 9, 6, 0, 3, 3, 0,
       3, 2, 1, 9, 3, 8, 8, 3, 8, 9, 7, 8, 0, 7, 1,

In [5]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
x_train

array([[ 0.08239042,  0.69742594, -0.61428834, ...,  0.10873433,
        -0.39380116,  0.34253897],
       [ 0.90778593, -0.42928155, -0.55685707, ..., -0.46936952,
        -1.40352797, -0.11038481],
       [-2.01849352, -0.23136227, -1.33232802, ...,  0.95385817,
         0.61289771,  1.81522969],
       ...,
       [ 0.86700697,  0.54063469,  1.81830724, ...,  1.56494688,
         0.9834829 ,  0.9088723 ],
       [-0.98477293, -0.06645381, -0.64898999, ..., -0.06100823,
        -0.20127231,  0.31504643],
       [ 0.76049484, -1.05265172,  0.28366503, ..., -0.87753751,
         0.61010253, -0.66633846]])

In [6]:
model = LGBMClassifier(boosting_type= 'gbdt', learning_rate=0.2, max_depth= 7, num_leaves=150)
model.fit(x_train,y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.003769 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14313
[LightGBM] [Info] Number of data points in the train set: 800, number of used features: 57
[LightGBM] [Info] Start training from score -2.302585
[LightGBM] [Info] Start training from score -2.302585
[LightGBM] [Info] Start training from score -2.302585
[LightGBM] [Info] Start training from score -2.302585
[LightGBM] [Info] Start training from score -2.302585
[LightGBM] [Info] Start training from score -2.302585
[LightGBM] [Info] Start training from score -2.302585
[LightGBM] [Info] Start training from score -2.302585
[LightGBM] [Info] Start training from score -2.302585
[LightGBM] [Info] Start training from score -2.302585
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] N

LGBMClassifier(learning_rate=0.2, max_depth=7, num_leaves=150)

In [7]:
predictions = model.predict(x_test)
accuracy = accuracy_score(y_test, predictions)
print('Accuracy: %.2f%%' % (accuracy*100))
print(classification_report(y_test, predictions))

Accuracy: 72.00%
              precision    recall  f1-score   support

           0       0.85      0.85      0.85        20
           1       0.90      0.90      0.90        20
           2       0.64      0.80      0.71        20
           3       0.67      0.40      0.50        20
           4       0.60      0.75      0.67        20
           5       0.89      0.85      0.87        20
           6       0.94      0.85      0.89        20
           7       0.74      0.70      0.72        20
           8       0.57      0.65      0.60        20
           9       0.47      0.45      0.46        20

    accuracy                           0.72       200
   macro avg       0.73      0.72      0.72       200
weighted avg       0.73      0.72      0.72       200



In [8]:
cm=confusion_matrix(y_test, predictions)
category_names = ["blues","classical","country","disco","hiphop","jazz","metal","pop","reggae","rock"]
true_positives = np.diag(cm)
false_positives = np.sum(cm, axis=0) - true_positives
false_negatives = np.sum(cm, axis=1) - true_positives
accuracy_per_label = true_positives / (true_positives + false_negatives)
print(confusion_matrix(y_test, predictions))
for i, accuracy in enumerate(accuracy_per_label):
    category_name = category_names[i]
    print("Accuracy for {}: {:.4f}".format(category_name, accuracy))

[[17  0  1  0  0  0  0  0  1  1]
 [ 0 18  0  0  0  1  0  0  0  1]
 [ 1  0 16  0  0  1  0  0  1  1]
 [ 0  1  0  8  6  0  0  4  0  1]
 [ 1  0  1  1 15  0  0  0  2  0]
 [ 0  1  0  0  0 17  0  0  0  2]
 [ 1  0  0  0  0  0 17  0  0  2]
 [ 0  0  2  0  1  0  0 14  3  0]
 [ 0  0  2  1  1  0  0  1 13  2]
 [ 0  0  3  2  2  0  1  0  3  9]]
Accuracy for blues: 0.8500
Accuracy for classical: 0.9000
Accuracy for country: 0.8000
Accuracy for disco: 0.4000
Accuracy for hiphop: 0.7500
Accuracy for jazz: 0.8500
Accuracy for metal: 0.8500
Accuracy for pop: 0.7000
Accuracy for reggae: 0.6500
Accuracy for rock: 0.4500
