In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!pip install lazypredict

In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from lightgbm import LGBMClassifier
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
data = pd.read_csv("/content/drive/MyDrive/features_3_sec.csv")
df = data.sample(frac=1).reset_index(drop=True)
df.head()

filename  length  chroma_stft_mean  chroma_stft_var  rms_mean  \
0    pop.00066.4.wav   66149          0.388605         0.084996  0.231507   
1   jazz.00092.9.wav   66149          0.223066         0.097990  0.107239   
2  metal.00032.2.wav   66149          0.477698         0.066282  0.133774   
3  metal.00088.2.wav   66149          0.405987         0.092436  0.126362   
4   rock.00022.4.wav   66149          0.387875         0.078612  0.180379   

    rms_var  spectral_centroid_mean  spectral_centroid_var  \
0  0.004826             3028.338300           1.174004e+06   
1  0.000987             4273.098132           1.077251e+06   
2  0.000645             2542.632561           2.026325e+05   
3  0.003870             2092.952645           5.325680e+05   
4  0.001631             2191.468959           1.945252e+05   

   spectral_bandwidth_mean  spectral_bandwidth_var  ...  mfcc16_var  \
0              3342.191329           100252.036066  ...   38.893227   
1              3141.108073            57493.323901  ...   55.472553   
2              2190.488081            55577.294906  ...   18.485477   
3              2144.801064           103683.963899  ...   30.074339   
4              2115.183003            59782.027095  ...   46.632908   

   mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  \
0     1.093173  104.137634    -2.664141   88.287376    -0.122730   67.860397   
1    -6.575345   16.514626     1.380429   42.711636    20.741129  100.786377   
2   -13.634504   34.955769     1.435127   19.866688    -1.927894   20.404568   
3    -8.582495   30.162340    -0.980684   26.697878     0.249167   37.676701   
4    -5.244864   39.155296     2.295769   27.865902    -5.917521   30.856937   

   mfcc20_mean  mfcc20_var  label  
0     2.778727   81.561913    pop  
1   -17.499990   33.833736   jazz  
2    -0.463197   17.528139  metal  
3    -3.475801   21.728697  metal  
4    -3.053838   27.441746   rock  

[5 rows x 60 columns]

In [21]:
dummy = df.drop(['filename', 'length'], axis=1)
column_name = 'label'
label_encoder = LabelEncoder()
dummy[column_name] = label_encoder.fit_transform(dummy[column_name])
corr = dummy.corr()
corr_style = corr.style.background_gradient(cmap='coolwarm')
display(corr_style)

In [7]:
label_encoder = LabelEncoder()
target = "label"
x = df.drop(['filename', 'length',target], axis=1)
y = df[target]
y= label_encoder.fit_transform(y)
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=0.8, random_state=100)
y

array([7, 3, 5, ..., 0, 0, 3])

In [8]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
x_train

array([[ 0.25879486,  0.34771182,  1.80544582, ..., -0.85760257,
        -0.57065063, -0.68390099],
       [-0.22844685,  1.12587602, -0.01774581, ...,  0.25714037,
         0.68534788,  0.00660484],
       [-0.10127454,  1.18134052, -0.46575897, ...,  0.09685155,
        -0.36041918,  0.89591963],
       ...,
       [-0.32427007,  0.72952411,  1.45828582, ...,  0.37975343,
         0.85090947, -0.20560639],
       [-0.73895391,  0.6790055 ,  0.48712168, ..., -0.6292927 ,
        -0.47660985, -0.64529929],
       [ 0.84781952, -0.14029105,  1.19552582, ..., -0.79384673,
         1.9488413 , -0.63914817]])

In [9]:
model = LGBMClassifier(boosting_type= 'gbdt', learning_rate=0.2, max_depth= 7, num_leaves=150)
model.fit(x_train,y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.009440 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 14329
[LightGBM] [Info] Number of data points in the train set: 7992, number of used features: 57
[LightGBM] [Info] Start training from score -2.296597
[LightGBM] [Info] Start training from score -2.305342
[LightGBM] [Info] Start training from score -2.285465
[LightGBM] [Info] Start training from score -2.291634
[LightGBM] [Info] Start training from score -2.274456
[LightGBM] [Info] Start training from score -2.304088
[LightGBM] [Info] Start training from score -2.312898
[LightGBM] [Info] Start training from score -2.346320
[LightGBM] [Info] Start training from score -2.286696
[LightGBM] [Info] Start training from score -2.324342
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] 

LGBMClassifier(learning_rate=0.2, max_depth=7, num_leaves=150)

In [10]:
predictions = model.predict(x_test)
accuracy = accuracy_score(y_test, predictions)
print('Accuracy: %.2f%%' % (accuracy*100))
print(classification_report(y_test, predictions))

Accuracy: 91.49%
              precision    recall  f1-score   support

           0       0.93      0.89      0.91       196
           1       0.92      0.97      0.94       201
           2       0.84      0.89      0.87       184
           3       0.88      0.91      0.89       191
           4       0.95      0.89      0.92       176
           5       0.93      0.92      0.92       202
           6       0.95      0.96      0.95       209
           7       0.94      0.94      0.94       235
           8       0.93      0.89      0.91       188
           9       0.88      0.89      0.88       216

    accuracy                           0.91      1998
   macro avg       0.92      0.91      0.91      1998
weighted avg       0.92      0.91      0.92      1998



In [27]:
cm=confusion_matrix(y_test, predictions)
category_names = ["blues","classical","country","disco","hiphop","jazz","metal","pop","reggae","rock"]
true_positives = np.diag(cm)
false_positives = np.sum(cm, axis=0) - true_positives
false_negatives = np.sum(cm, axis=1) - true_positives
accuracy_per_label = true_positives / (true_positives + false_negatives)
print(confusion_matrix(y_test, predictions))
for i, accuracy in enumerate(accuracy_per_label):
    category_name = category_names[i]
    print("Accuracy for {}: {:.4f}".format(category_name, accuracy))

[[175   1   7   2   2   4   2   0   2   1]
 [  0 194   1   0   0   4   0   0   0   2]
 [  6   1 164   3   0   3   0   1   1   5]
 [  1   0   5 173   0   1   0   4   3   4]
 [  1   0   2   3 157   0   3   6   1   3]
 [  2  10   3   0   0 185   0   0   0   2]
 [  1   0   0   2   1   0 200   0   0   5]
 [  0   1   1   7   0   1   0 221   3   1]
 [  0   2   6   1   4   0   1   4 167   3]
 [  3   1   6   5   1   2   4   0   2 192]]
Accuracy for blues: 0.8929
Accuracy for classical: 0.9652
Accuracy for country: 0.8913
Accuracy for disco: 0.9058
Accuracy for hiphop: 0.8920
Accuracy for jazz: 0.9158
Accuracy for metal: 0.9569
Accuracy for pop: 0.9404
Accuracy for reggae: 0.8883
Accuracy for rock: 0.8889
