In [45]:
import pandas as pd
import numpy as np


df = pd.read_csv('/home/khangpt/MUSIC-GEN-PROJ/GTZAN/Data/features_30_sec.csv')
X = df.iloc[:,2:-1]
y = df.iloc[:,-1]

In [46]:
df.label = pd.Categorical(df.label)
y = np.array(df.label.cat.codes)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,

In [47]:
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import classification_report

import pickle

KNN = make_pipeline(MinMaxScaler(),KNeighborsClassifier(n_neighbors=1))
SVM = make_pipeline(MinMaxScaler(),SVC(kernel='rbf', gamma='scale', C=50,probability=True))
NB = make_pipeline(MinMaxScaler(),GaussianNB())
SGD = make_pipeline(MinMaxScaler(),SGDClassifier(max_iter=5000, random_state=0))
TREE = make_pipeline(MinMaxScaler(),DecisionTreeClassifier())
LG = make_pipeline(MinMaxScaler(),LogisticRegression(random_state=0, solver='lbfgs', multi_class='multinomial'))
MLP = make_pipeline(MinMaxScaler(),MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5000, 10), random_state=1))

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=42)

In [49]:
y_test

array([5, 7, 7, 6, 4, 6, 6, 5, 8, 1, 8, 0, 6, 9, 9, 8, 2, 8, 7, 3, 5, 1,
       3, 5, 2, 2, 1, 9, 9, 9, 3, 1, 6, 4, 3, 1, 6, 5, 9, 0, 3, 0, 3, 9,
       2, 2, 9, 6, 4, 8, 5, 8, 2, 5, 0, 0, 6, 0, 2, 8, 2, 0, 5, 2, 6, 6,
       6, 8, 0, 5, 1, 4, 5, 7, 2, 2, 6, 0, 5, 3, 6, 0, 2, 0, 3, 5, 9, 7,
       7, 3, 3, 4, 5, 2, 7, 4, 7, 0, 0, 8, 7, 3, 9, 2, 6, 6, 5, 9, 1, 9,
       5, 8, 9, 8, 0, 4, 1, 9, 5, 2, 8, 4, 7, 2, 2, 5, 5, 4, 8, 8, 5, 8,
       2, 9, 5, 0, 1, 2, 0, 0, 0, 2, 7, 2, 8, 9, 8, 2, 8, 3, 6, 1, 9, 4,
       9, 4, 3, 6, 0, 8, 5, 7, 6, 6, 8, 6, 2, 6, 3, 3, 3, 4, 1, 9, 4, 3,
       2, 2, 8, 6, 4, 6, 3, 5, 8, 1, 3, 3, 9, 7, 9, 8, 6, 1, 2, 4, 3, 2,
       6, 0, 0, 5, 6, 5, 8, 5, 1, 9, 4, 8, 0, 1, 9, 8, 6, 3, 6, 2, 9, 7,
       3, 7, 9, 0, 8, 0, 5, 3, 9, 5, 3, 9, 4, 5, 0, 0, 2, 9, 1, 3, 0, 2,
       5, 7, 3, 1, 4, 0, 0, 2, 0, 9, 7, 8, 3, 3, 5, 9, 9, 0, 7, 4, 0, 2,
       3, 8, 7, 3, 6, 3, 4, 1, 9, 2, 5, 0, 1, 6, 0, 7, 5, 7, 2, 2, 2, 7,
       3, 4, 2, 9, 9, 7, 5, 4, 3, 4, 9, 4, 0, 1], d

In [50]:
voting_clf = VotingClassifier(
    estimators=[('svm',SVM),
                ('knn',KNN),
                ('nb',NB),
                ('sgd',SGD),
                ('tree',TREE),
                ('LG',LG),
                ('mlp',MLP)],
                voting='hard'
)
voting_clf.fit(X_train,y_train)
# for name,clf in voting_clf.named_estimators_.items():
#     print(clf.score(X_test,y_test))

/home/khangpt/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/khangpt/anaconda3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:541: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)


VotingClassifier(estimators=[('svm',
                              Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                                              ('svc',
                                               SVC(C=50, probability=True))])),
                             ('knn',
                              Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                                              ('kneighborsclassifier',
                                               KNeighborsClassifier(n_neighbors=1))])),
                             ('nb',
                              Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                                              ('gaussiannb', GaussianNB())])),
                             ('sgd',
                              Pipeline(steps=[(...
                                              ('decisiontreeclassifier',
                                               DecisionTreeClassifier())])),
                             ('LG',
                              Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                                              ('logisticregression',
                                               LogisticRegression(multi_class='multinomial',
                                                                  random_state=0))])),
                             ('mlp',
                              Pipeline(steps=[('minmaxscaler', MinMaxScaler()),
                                              ('mlpclassifier',
                                               MLPClassifier(alpha=1e-05,
                                                             hidden_layer_sizes=(5000,
                                                                                 10),
                                                             random_state=1,
                                                             solver='lbfgs'))]))])

In [51]:
pred = voting_clf.predict(X_test)
print(accuracy_score(pred,y_test))
# SVM.fit(X_train, y_train)
# KNN.fit(X_train, y_train)
# print(SVM.score(X_test, y_test))
# print(KNN.score(X_test, y_test))
print(accuracy_score(pred,y_test))
print(classification_report(pred, y_test))

0.7033333333333334
0.7033333333333334
              precision    recall  f1-score   support

           0       0.83      0.60      0.70        48
           1       1.00      0.87      0.93        23
           2       0.70      0.72      0.71        36
           3       0.56      0.76      0.64        25
           4       0.67      0.62      0.64        26
           5       0.73      1.00      0.84        24
           6       0.90      0.71      0.79        38
           7       0.74      0.85      0.79        20
           8       0.52      0.54      0.53        28
           9       0.51      0.56      0.54        32

    accuracy                           0.70       300
   macro avg       0.72      0.72      0.71       300
weighted avg       0.72      0.70      0.70       300



In [52]:
from sklearn.metrics import classification_report
SVM.fit(X_train, y_train)
pred_svm = SVM.predict(X_test)
print(accuracy_score(pred_svm,y_test))
print(classification_report(pred_svm, y_test))

0.7433333333333333
              precision    recall  f1-score   support

           0       0.77      0.84      0.81        32
           1       1.00      0.95      0.98        21
           2       0.78      0.74      0.76        39
           3       0.74      0.68      0.70        37
           4       0.75      0.58      0.65        31
           5       0.85      0.97      0.90        29
           6       0.93      0.80      0.86        35
           7       0.70      0.80      0.74        20
           8       0.45      0.54      0.49        24
           9       0.54      0.59      0.57        32

    accuracy                           0.74       300
   macro avg       0.75      0.75      0.75       300
weighted avg       0.75      0.74      0.75       300



In [53]:
KNN.fit(X_train, y_train)
pred_knn = KNN.predict(X_test)
print(accuracy_score(pred_knn,y_test))
print(accuracy_score(pred_knn,y_test))
print(classification_report(pred_knn, y_test))

0.6566666666666666
0.6566666666666666
              precision    recall  f1-score   support

           0       0.71      0.81      0.76        31
           1       0.85      0.89      0.87        19
           2       0.68      0.60      0.63        42
           3       0.47      0.53      0.50        30
           4       0.71      0.53      0.61        32
           5       0.67      0.76      0.71        29
           6       0.87      0.84      0.85        31
           7       0.74      0.74      0.74        23
           8       0.48      0.54      0.51        26
           9       0.51      0.49      0.50        37

    accuracy                           0.66       300
   macro avg       0.67      0.67      0.67       300
weighted avg       0.66      0.66      0.66       300



In [54]:
pred_knn

array([9, 7, 2, 6, 4, 6, 6, 5, 8, 1, 4, 0, 6, 9, 3, 6, 2, 5, 7, 3, 3, 1,
       3, 5, 2, 2, 1, 9, 4, 9, 3, 1, 6, 8, 3, 1, 6, 5, 0, 0, 3, 0, 2, 9,
       3, 2, 9, 6, 7, 8, 5, 4, 2, 5, 0, 0, 6, 8, 2, 8, 2, 0, 5, 2, 6, 9,
       6, 8, 2, 2, 1, 4, 5, 7, 9, 2, 6, 0, 2, 3, 3, 9, 4, 0, 3, 5, 5, 2,
       0, 4, 4, 4, 5, 7, 7, 4, 7, 2, 9, 8, 7, 3, 9, 2, 6, 6, 9, 9, 1, 9,
       5, 8, 8, 6, 0, 4, 1, 9, 5, 2, 8, 4, 4, 2, 7, 7, 9, 7, 4, 3, 0, 3,
       2, 9, 5, 0, 1, 3, 0, 0, 0, 5, 7, 2, 8, 8, 8, 0, 6, 4, 6, 1, 9, 4,
       9, 4, 9, 6, 0, 3, 5, 7, 6, 6, 4, 0, 2, 6, 9, 2, 3, 8, 1, 2, 4, 6,
       2, 2, 4, 6, 4, 4, 0, 5, 4, 1, 3, 4, 2, 7, 5, 9, 6, 5, 2, 4, 7, 2,
       6, 0, 0, 5, 6, 5, 8, 5, 1, 9, 4, 8, 9, 1, 9, 8, 6, 9, 6, 9, 2, 7,
       3, 7, 3, 0, 8, 2, 5, 9, 9, 5, 3, 9, 8, 5, 0, 0, 9, 8, 1, 3, 0, 2,
       1, 7, 9, 5, 3, 0, 0, 2, 2, 9, 7, 2, 3, 3, 1, 6, 9, 2, 7, 4, 0, 2,
       9, 8, 7, 9, 6, 9, 4, 1, 2, 2, 5, 2, 1, 6, 0, 3, 8, 7, 3, 2, 8, 3,
       3, 4, 2, 8, 3, 7, 5, 4, 4, 4, 8, 8, 0, 5], d

In [55]:
y_test

array([5, 7, 7, 6, 4, 6, 6, 5, 8, 1, 8, 0, 6, 9, 9, 8, 2, 8, 7, 3, 5, 1,
       3, 5, 2, 2, 1, 9, 9, 9, 3, 1, 6, 4, 3, 1, 6, 5, 9, 0, 3, 0, 3, 9,
       2, 2, 9, 6, 4, 8, 5, 8, 2, 5, 0, 0, 6, 0, 2, 8, 2, 0, 5, 2, 6, 6,
       6, 8, 0, 5, 1, 4, 5, 7, 2, 2, 6, 0, 5, 3, 6, 0, 2, 0, 3, 5, 9, 7,
       7, 3, 3, 4, 5, 2, 7, 4, 7, 0, 0, 8, 7, 3, 9, 2, 6, 6, 5, 9, 1, 9,
       5, 8, 9, 8, 0, 4, 1, 9, 5, 2, 8, 4, 7, 2, 2, 5, 5, 4, 8, 8, 5, 8,
       2, 9, 5, 0, 1, 2, 0, 0, 0, 2, 7, 2, 8, 9, 8, 2, 8, 3, 6, 1, 9, 4,
       9, 4, 3, 6, 0, 8, 5, 7, 6, 6, 8, 6, 2, 6, 3, 3, 3, 4, 1, 9, 4, 3,
       2, 2, 8, 6, 4, 6, 3, 5, 8, 1, 3, 3, 9, 7, 9, 8, 6, 1, 2, 4, 3, 2,
       6, 0, 0, 5, 6, 5, 8, 5, 1, 9, 4, 8, 0, 1, 9, 8, 6, 3, 6, 2, 9, 7,
       3, 7, 9, 0, 8, 0, 5, 3, 9, 5, 3, 9, 4, 5, 0, 0, 2, 9, 1, 3, 0, 2,
       5, 7, 3, 1, 4, 0, 0, 2, 0, 9, 7, 8, 3, 3, 5, 9, 9, 0, 7, 4, 0, 2,
       3, 8, 7, 3, 6, 3, 4, 1, 9, 2, 5, 0, 1, 6, 0, 7, 5, 7, 2, 2, 2, 7,
       3, 4, 2, 9, 9, 7, 5, 4, 3, 4, 9, 4, 0, 1], d